### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by hao-lh** [quinghui/emuch.net#1]
Hi,

First thanks a lot for making this code open source, the emuch.net has changed a lot during the last several months, and the code does not work anymore, I was wondering if you have any plans to update it?
Thanks!

**Comment by quinghui** [comment]
Thanks for your feedback. The issue is fixed for the **emuch_coins.py**. Please feel free to try it and let me know if working for you.

**Comment by hao-lh** [comment]
Hi quinghui,
Thanks for your quick response, and I encountered with the following errors:
![screen shot 2016-11-15 at 6 45 36 pm copy](https://cloud.githubusercontent.com/assets/14138581/20303017/6dedc64a-ab64-11e6-82e0-357620843a09.jpg)

Also, iOS client can allow each user with 5 coins every day, would it be possible to revised user-agent option to achieve this, thanks!

**Comment by quinghui** [comment]
Hi Hao-lh,

Thanks for the feedback. Just for clarity a few things
- the Python scripts only support Python3;
- for emuch_coins.py, you would need to create your own file emuch_cookies.json, based on  README. This  https://kb.iu.edu/d/ajfi might help you to get the cookies.
  
  I'm not familiar with ios, so on idea for that stuff.

Thanks,

**Comment by quinghui** [comment]
BTW, I'm not familiar with ios, so on idea for that stuff.
